### ISSUE TITLE
Completed the Assignment

### ISSUE THREAD

**Issue by 7ruth** [ga-dc/cash-register#3]
Had trouble with git branches so had to make a separate ripo from which I couldnt do a pull request.

Completed assignment is at the link below:

https://github.com/7ruth/RegisterGameUsingComponentsApproach

**Comment by andrewsunglaekim** [comment]
Great job on this assignment, cool feature for multiple cash registers. One convention we follow as developers is `el` for dom elements that pertain to the main focus of the component. 👍
